<?php

/*
 * @file
 * this module creates an artwork entity
 */

/**
 * Implements hook_entity_info 
 */
function artwork_entity_info() {
  $return = array();
  $return['artwork'] = array(
    'label' => t('artwork'),
    'controller class' => 'ArtworkController',
    'base table' => 'artwork',
    'revision table' => 'artwork_revision',
    'uri callback' => 'artwork_uri',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'aid',
      'revision' => 'vid',
      'bundle' => 'type',
      'label' => 'title',
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'static cache' => TRUE,
    'bundles' => array(),
    'view modes' => array(
      'full' => array(
        'label' => t('Full Content'),
        'custom setting' => FALSE,
      ),
      'teaser' => array(
        'label' => t('Teaser'),
        'custom settings' => FALSE,
      ),
    ),
  );
  
  foreach(artwork_types() as $type => $info ) {
    $return['artwork']['bundels'][$type] = array(
      'label' => $info->name,
      'admin' => array(
        'path' => 'admin/structure/artworks/%artwork_work',
        'real path' => 'admin/structure/artworks/manage/' . str_replace('_', '-', $type),
        'bundle argument' => 4, 
        'access arguments' => array('administer artworks'),
      ),
    );
  }
  
  return $return;
}
