<?php

/*
 * @file
 * User Warn module file
 * 
 * This module allows site administrators to email a stock warning to a specified user or users 
 * Adminstrators can configure the defualt message including token support
 * 
 */

/**
 * implements hook_help 
 */
function user_warn_help ($path, $arg) {
  if ($path == 'admin/help#user_warn') {
    return t('User Warn allows site adminitrators to send a standard
   e-mail to site users to notify them of improper behavior.');
  }
}

/**
 * Implementation of hook_menu 
 */
function user_warn_menu () {
  $items = array();
  
  $items['admin/config/people/user_warm'] = array(
    'title' => 'User Warn',
    'description' => t('Warn users via email about bad behavior'),
    'page_callback' => drupal_get_form,
    'page_arguments' => array('user_warn_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );
  
    $items['user/%/user_warm'] = array(
    'title' => 'Warn',
    'description' => t('Warn a user via email about bad behavior'),
    'page_callback' => drupal_get_form,
    'page_arguments' => array('user_warn_confirm_form', 1),
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
  );
}

/**
 *  From builder function to create and display the user warn confioguration settings form
 * @param type $form - array to hold form field
 * @param type $form_state - be sure to pass by reference &$form_state 
 */
function user_warn_form ($form, &$form_state) {
  // text field for the mail subject 
  $form['user_warn_e-mail_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Warning e-mail subject'),
    '#description' => t('The subject of the e-mail which will be sent
to users.'),
    '#size' => 40, 
    '#maxlength' => 120,
    '#required' => TRUE,
  );
  // Textarea for body of the email
  $form['user_warn_e-mail_text'] = array(
    '#type' => 'textarea',
    '#rows' => 10,
    '#columns' => 40, 
    '#title' => t('Warning e-mail text'),
    '#required' => TRUE,
    '#description' => t('Text to send to users as a warning.'),
  );
  //Checkbox to indicate if we should bcc the sute admin on the email message
  $form['user_warn_bcc'] = array(
    '#type' => 'checkbox',
    '#title' => t('BCC admin on all e-mails'),
    '#description' => t('Inidcates whether the admin should be copied on all warning emails'),
  );
  
  $form['submit']  = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
  );
  
  return $form;
}