<?php

/**
* @file
* Enables a single user blog
*/

define('SINGLE_BLOG_NODE_TYPE', 'article');
define('SINGLE_BLOG_LIST_COUNT', 3);

/**
* Returns a list of blog entries
*
* @param $number 
* The number of blog entries to return
*
* @return 
* a result set object containing the list of blog entries
*/
function single_blog_list ($number) {
  $query = db_select('node', 'n')
  ->fields('n', array('nid', 'title', 'created', 'uid'))
  ->condition('type', SINGLE_BLOG_NODE_TYPE)
  ->condition('status', 1)
  ->orderBy('created', 'DESC')
  ->range(0, $number)
  ->addTag('node_access')
  ->execute();
  return $query;
}

/**
* Implements hook_block_info
*/
function single_blog_block_info () {
  $blocks = array();

  $blocks['recent'] = array(
    'info' => t('Recent Blog Posts'),
  );
  return $blocks;
}

/**
* Implements hook_block_view
* 
* @param $delta
* the name of the requestedblock
*/

function single_blog_block_view($delta = '') {
  $block = array(
    'subject' => '',
    'content' => '',
  );

  if ($delta == 'recent' ) {
    $block['subject'] = t('Recent Blog Posts');    
    if(user_access('access content')) {
      $result = single_blog_list(SINGLE_BLOG_LIST_COUNT);
      
      // Create links for each blog entry
      $items = array();
      foreach ( $result as $node) {
        $items[] = array(
          'data' => array(
           '#theme' => 'item_list__single_blog',
           '#node' => $node,
           '#href' => 'node/' . $node->nid,
          ),
          'class' => array('node-' . $node->nid),
        );
      }
      if (!empty($items)) {
        $block['content']['list'] = array(
          '#theme' => 'item_list__single_blog',
          '#items' => $items,
          '#pre_render' => array('single_blog_list_child_render'),
        );
        $block['content']['more'] = array(
          '#theme' => 'more_link',
          '#url' => 'blog',
          '#title' => t('Read the latest blog posts'),
        );
        $block['content']['#attached']['css'][] = drupal_get_path('module', 'single_blog') . '/single_blog.css';
      }  
    }
  }
  return $block;
}
/**
* take the array we created in single_blog_list and single_blog_block_view and render it as html 
* this is to overcome the fact that theme_item_list()  will not take a render element
*/
function single_blog_list_child_render ($elements) {
  foreach (array_keys($elements['#items']) AS $key) {
    if (is_array($elements['#items'][$key]['data'])) {
      $elements['#items'][$key]['data'] = drupal_render($elements['#items'][$key]['data']);
      
    }
  }
  return $elements;
}

/**
* implements hook_theme
*/
function single_blog_theme () {
  return array(
    'single_blog_block_item' => array(
      'vars' => array(
        'node' => NULL,
      ),
      'template' => 'single_blog_block_item',
    ),
  );
}


